// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axadrchsdikzsgcbldcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4YWRyY2hzZGlrenNnY2JsZGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTkwNDcsImV4cCI6MjA4ODUzNTA0N30.xk0Tb6sg30rYMTj7O1oJikpwijstNhN_glilHhKJyuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});